function imStack = loadKnkImages(imFile, imNums)
% LOAD IMAGES: Load unprocessed stimulus images from Kay et al. dataset
%
% Input:
%   imFile: path to the stimuli.mat file from the SOC project,
%           e.g. fullfile(rootpath, 'data/input/stimuli.mat');
%   imNums: which image categories to load, C categories. These images must
%           be stimulus categories which have the same raw image size and
%           same number of frames.
%
% Output:
%   imStack: a matrix of images, X * Y * C * F
%
% (CO note: Loading knk's stimuli is necessary because the pilot stimuli
%  used in April were generated by combining existing stimuli. Later
%  experiments used made-from-scratch stimuli, as shown in the later
%  stimulusgen scripts.)

    assert(ischar(imFile), 'imFile must be a string');
    assert(isvector(imNums), 'imNums must be a vector');
    
    load(imFile, 'images');
    
    stimCell = images(imNums);
    imStack = cellToStack(stimCell);
    
end